version: 1.0.{build}
branches:
  except:
  - /develop.*/
skip_tags: true
image: Visual Studio 2019
clone_depth: 2
environment:
  COVERALLS_REPO_TOKEN:
    secure: REZBaTQymYRQdGEJgpMw1O75r2pVJ7yNlhwLXwoj1NWaEYs5sTwpPdGlvjlWAf13
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    $ErrorActionPreference = 'Continue'

    & dotnet tool restore

    & dotnet fake run .\Build\setup.fsx

    & dotnet fake run .\Build\build.fsx

    $save = $LASTEXITCODE
    
    $error.Clear()

    Write-Host "Exit code $save"

    if ($save -ne 0) { exit $save }
test:
  assemblies:
    - '**\*.no.tests.dll'
artifacts:
- path: _Packagin*\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: o/8UywbOY88VOMoi6Xk2epQZppAkgJLKsb6SRXhyY+Z2SqvJe6N8tazHs3WbesgI
  on:
    branch: /release.*/